<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Инцидент+</title>
    <?php
    $this->assets->addCss('css/bootstrap.css');
    $this->assets->addCss('css/animate.css');
    $this->assets->addCss('css/style.css');
    $this->assets->addJs('js/jquery-1.11.2.js');
    $this->assets->addJs('js/bootstrap.js');
    ?>
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/animate.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/jquery-1.11.2.js"></script>
    <script src="/js/bootstrap.js"></script>
</head>
<body>

<div class="modal-window text-center animated bounceInDown" id="modal-win">
    <?php echo $this->tag->form("adminPage/report"); ?>
    <!--<form action="report.phtml" class="form-horizontal">-->
        <div class="form-group">
            <label class="control-label">Введите логин и пароль</label>
            <div class="col-lg-offset-2 col-lg-8" style="margin-top: 20px">
                <input type="login" class="form-control login-form" required placeholder="Введите логин" >
                <input type="password" class="form-control login-form" style="margin-top: 10px;" placeholder="Введите пароль" required>
            </div>
        </div>

        <div class="form-group">
            <div>
                <input type="submit" class="btn btn-primary smena-button" id="cancel" value="Войти"/>
                <a href="/index.phtml" class="btn btn-primary smena-button smena-button-otmena">Отмена</a>
            </div>
        </div>
    </form>
</div>
<div class="overlay" id="overl"></div>

<script src="js/animate.js" type="text/javascript"></script>
<script src="/js/search.js" type="text/javascript"></script>
<script src="/js/modalWindowInput.js" type="text/javascript"></script>
</body>
</html>