<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Инцидент+</title>
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/animate.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/jquery-1.11.2.js"></script>
    <script src="/js/bootstrap.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-10 col-md-10 col-sm-10">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand logo" href="/index.html">
                        <img src="/img/logo.png" width="100%" alt="Logo">
                    </a>
                </div>
                <div class="collapse navbar-collapse navbar-right" id="navbar-main">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="/index.html" class="go_search">Статистика</a></li>
                        <!--<li><a id="smena" class="smena animated">Пересменка</a></li>-->
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>

<div class="container-fluid main-container">
    <div class="row incident-color-block" style="padding-top: 20px">
        <div class="col-lg-12 col-md-12 col-sm-12 content-incident" style="padding-left: 50px; padding-right: 50px;">
            <div class="col-lg-3 col-md-5 col-sm-5 filter-block">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <?php echo $this->tag->form("adminPage/request"); ?>
                        <label class="control-label">Введите дату</label>
                        <div style="margin-top: 20px">
                            <input type="text" id="beginDate" name="beginDate" class="select_spec date" placeholder="дата от"
                               data-lang="ru" data-years="2017-2022" data-format="YYYY-MM-DD" data-sundayfirst="false">
                        </div>

                        <div style="margin-top: 20px">
                            <input type="text" id="endDate" name="endDate" class="select_spec date" placeholder="дата до"
                                   data-lang="ru" data-years="2017-2022" data-format="YYYY-MM-DD" data-sundayfirst="false">
                        </div>

                        <div style="margin-top: 20px" class="form-group">
                            <label for="inputType" class="control-label">Выбор типа запроса</label>
                            <div>
                                <select class="custom-select mr-sm-2" id="inlineFormCustomSelect" name="inputType">
                                    <option value="1">По шагам</option>
                                    <option value="2">По инцидентам</option>
                                    <option value="3">По типам инцидентов</option>
                                </select>
                            </div>
                        </div>

                        <div style="margin-top: 20px" class="form-group">
                            <input type="submit" class="btn btn-primary smena-button" id="cancel" value="Сформировать отчет"/>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>
</div>

<div class="container-fluid foot">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-3 col-md-3 col-sm-3">
            <img src="/img/logo.png" alt="Logo">
        </div>
        <div class="col-lg-7 col-md-7 col-sm-8 text-right foot-text">
            Программа для автоматизации действий оператора<br>
            по поиску и выполнению инструкций
        </div>
    </div>
</div>
<!--Календарь-->
    <?php
        echo $this->tag->javascriptInclude('/js/moment-with-locales.min.js');
        echo $this->tag->javascriptInclude('/js/ion.calendar.js');
        echo $this->tag->StyleSheetLink('/css/ion.calendar.css');
    ?>

    <script>
        $(".date").each(function(){
            $(this).ionDatePicker();
        });
    </script>
<!--Календарь-->

<script src="/js/animate.js" type="text/javascript"></script>
<script src="/js/search.js" type="text/javascript"></script>
<script src="/js/modalWindowInput.js" type="text/javascript"></script>
</body>
</html>