<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Инцидент+</title>
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/animate.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/jquery-1.11.2.js"></script>
    <script src="/js/bootstrap.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-10 col-md-10 col-sm-10">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand logo" href="/index.html">
                        <img src="/img/logo.png" width="100%" alt="Logo">
                    </a>
                </div>
                <div class="collapse navbar-collapse navbar-right" id="navbar-main">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="/index.html" class="go_search">Статистика</a></li>
                        <!--<li><a id="smena" class="smena animated">Пересменка</a></li>-->
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>

<div class="container-fluid main-container">
    <div class="row incident-color-block" style="padding-top: 20px">
        <div class="col-lg-12 col-md-12 col-sm-12 content-incident" style="padding-left: 50px; padding-right: 50px;">
            <div class="col-lg-9 col-md-12 col-sm-12 content-items">
                <div class="col-lg-12 col-md-12 col-sm-12 animated">
                    <?php echo $nameTable;?>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                        <?php
                            foreach ($title as $t)
                                echo "<th >".$t."</th >";
                        ?>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($data as $d){
                            echo "<tr>";

                            echo "<th scope=\"row\">".$d[1]."</th>";
                            echo "<td>".$d[2]."</td>";
                            echo "<td><strong>".$d[3]."</strong></td>";
                            echo "<td><strong>".$d[4]."</strong></td>";

                            echo "</tr>";
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="col-lg-3 col-md-5 col-sm-5 filter-block">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="col-lg-2 col-md-2 col-sm-2 text-right go-incident">
                        <a href="/adminPage/report">Вернуться</a>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

<div class="container-fluid foot">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-3 col-md-3 col-sm-3">
            <img src="/img/logo.png" alt="Logo">
        </div>
        <div class="col-lg-7 col-md-7 col-sm-8 text-right foot-text">
            Программа для автоматизации действий оператора<br>
            по поиску и выполнению инструкций
        </div>
    </div>
</div>

<!--Календарь-->
<?php
echo $this->tag->javascriptInclude('/js/moment-with-locales.min.js');
echo $this->tag->javascriptInclude('/js/ion.calendar.js');
echo $this->tag->StyleSheetLink('/css/ion.calendar.css');
?>

<script>
    $(".date").each(function(){
        $(this).ionDatePicker();
    });
</script>
<!--Календарь-->

<script src="/js/animate.js" type="text/javascript"></script>
<script src="/js/search.js" type="text/javascript"></script>
<script src="/js/modalWindowInput.js" type="text/javascript"></script>
</body>
</html>