<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Инцидент+</title>
    <?php
        $this->assets->addCss('css/bootstrap.css');
        $this->assets->addCss('css/animate.css');
        $this->assets->addCss('css/style.css');
        $this->assets->addJs('js/jquery-1.11.2.js');
        $this->assets->addJs('js/bootstrap.js');
    ?>
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/animate.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/jquery-1.11.2.js"></script>
    <script src="/js/bootstrap.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-10 col-md-10 col-sm-10">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand logo" href="index.phtml">
                        <img src="/img/logo.png" width="100%" alt="Logo">
                    </a>
                </div>
                <div class="collapse navbar-collapse navbar-right" id="navbar-main">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.phtml" class="go_search">Поиск инструкции</a></li>
                        <li><a id="smena" class="smena animated">Пересменка</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>

<div class="container-fluid main-container">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-6 col-md-6 col-sm-7">
            <div class="title-search">
                НАЧАЛЬНАЯ ФОРМА ПОИСКА<br>
                ИНСТРУКЦИЙ
            </div>
            <div class="desc-search">
                Здесь вы сможете найти инструкцию, соответствующую<br>
                имеющемуся инциденту и открыть ее на выполнение
            </div>
            <div class="form-block">
                <?php echo $this->tag->form("searchPage/find"); ?>

                    <div class="col-lg-10 col-md-10 col-sm-10" style="padding: 0;">
                        <input id="url" name="url" class="form-control" type="text" placeholder="Введите название инструкции">
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-2" style="padding: 0;">
                        <input type="submit" class="btn btn-primary text-center form-control2 animated" value="Найти">
                    </div>
                </form>
                <ul id="result" class="list-group animated">

                </ul>
            </div>

        </div>
        <!--<div class="col-lg-4 col-md-4 col-sm-4 firefighter animated bounceInDown">
            <img src="img/firefighter.png" width="100%" alt="Пожарник">
        </div>-->
    </div>
    <div class="row row-type-incident">
        <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-3 col-md-3 col-sm-5">
            <div class="type-incident">
                <div class="main-title-incident">
                    Активные
                </div>
                <?php

                $incidient = Incidient::find(
                    [
                        'status = 0',       //запрос
                        'order' => 'id',    //сортировка
                        'offset'=> 0,       //смещение
                        //'limit' => 5,       //лимит записей//
                    ]
                );
                echo "<div class=\"list-group\">";
                foreach ($incidient as $inc){
                    $step=StepInIncidient::find(
                        [
                            'idIncidient = :ind:',       //запрос
                            'bind'=>[
                                'ind' => $inc->id,
                            ],
                            'order' => 'step',    //сортировка
                        ]
                    );

                    $summ=0;
                    $int=0;
                    foreach ($step as $s){
                        $summ++;
                        if($s->ending == NULL)
                            $int=$int+1;
                    }
                    $percent=0.0;
                    $percent=(($summ-$int)/$summ)*100.0;

                    $t=preg_split('/ /',$inc->dateStart);
                    $date_i=$t[0]; //дата
                    $time_i=$t[1]; //время

                    echo "<a href=\"/incidient/",$inc->id,"\"","class=\"list-group-item list-group-desc\">";
                        if($percent>30.0)
                            echo "<span class=\"percent pr-green\">",sprintf("%01.0f",$percent),"%";
                        else echo "<span class=\"percent pr-red\">",sprintf("%01.0f",$percent),"%";

                            ?><!--1.09.2018--></span><?php echo mb_substr($inc->title,0, 50).' ...';?>
                            <div class="desc-incident">
                            <div class="row title-tooltip-inc">
                                <div class="col-lg-12">
                                    <?php echo sprintf("%s",$inc->title);?>
                                </div>
                            </div>
                            <div class="row date-time-go">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Время начала</div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Дата начала</div>
                            </div>
                            <div class="row date-time-go-bold">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left"><?php echo sprintf("%.5s",$time_i);//переделать формат для часов?></div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left"><?php echo $date_i;//переделать формат для даты?></div>
                            </div>
                            <div class="row indication-block">
                                <div class="progress" style="height: 6px">
                                    <div class="progress-bar progress-bar-green" role="progressbar" style="width: <?php echo $percent,"%"?>" aria-valuenow="<?php echo $percent,"%"?>" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="indication text-center">Выполнено <?php echo sprintf("%01.2f",$percent),"%"?></div>
                            </div>
                        </div>
                    </a>
                        <?php
                }
                ?>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-5">
            <div class="type-incident inc-yellow">
                <div class="main-title-incident title-yellow">
                    Долгосрочные
                </div>
                <?php

                $incidient = Incidient::find(
                    [
                        'status = 1',       //запрос
                        'order' => 'id',    //сортировка
                        'offset'=> 0,       //смещение
                        //'limit' => 5,       //лимит записей
                    ]
                );
                echo "<div class=\"list-group\">";
                foreach ($incidient as $inc){

                $step=StepInIncidient::find(
                    [
                        'idIncidient = :ind:',       //запрос
                        'bind'=>[
                            'ind' => $inc->id,
                        ],
                        'order' => 'step',    //сортировка
                    ]
                );

                $summ=0;
                $int=0;
                foreach ($step as $s){
                    $summ++;
                    if($s->ending == NULL)
                        $int=$int+1;
                    //echo $s->id, "\n";
                    //echo $s->step, "\n", "</div>";
                }
                $percent=0.0;
                $percent=(($summ-$int)/$summ)*100.0;

                $t=preg_split('/ /',$inc->dateStart);
                $date_i=$t[0]; //дата
                $time_i=$t[1]; //время

                echo "<a href=\"/incidient/",$inc->id,"\"","class=\"list-group-item list-group-desc\">";
                if($percent>70.0)
                    echo "<span class=\"percent pr-yellow\">",sprintf("%01.0f",$percent),"%";
                else echo "<span class=\"percent pr-green\">",sprintf("%01.0f",$percent),"%";

                ?><!--1.09.2018--></span><?php echo mb_substr($inc->title,0, 50).' ...';?>
                <div class="desc-incident">
                    <div class="row title-tooltip-inc">
                        <div class="col-lg-12">
                            <?php echo sprintf("%s",$inc->title);?>
                        </div>
                    </div>
                    <div class="row date-time-go">
                        <div class="col-lg-6 col-md-6 col-sm-6 text-left">Время начала</div>
                        <div class="col-lg-6 col-md-6 col-sm-6 text-left">Дата начала</div>
                    </div>
                    <div class="row date-time-go-bold">
                        <div class="col-lg-6 col-md-6 col-sm-6 text-left"><?php echo sprintf("%.5s",$time_i);//переделать формат для часов?></div>
                        <div class="col-lg-6 col-md-6 col-sm-6 text-left"><?php echo $date_i;//переделать формат для даты?></div>
                    </div>
                    <div class="row indication-block">
                        <div class="progress" style="height: 6px">
                            <div class="progress-bar progress-bar-green" role="progressbar" style="width: <?php echo $percent,"%"?>" aria-valuenow="<?php echo $percent,"%"?>" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <div class="indication text-center">Выполнено <?php echo sprintf("%01.2f",$percent),"%"?></div>
                    </div>
                </div>
                </a>
                <?php
                }
                ?>
            </div>
                <!---->
            </div>
        </div>
        <div class="col-lg-offset-0 col-md-offset-0 col-sm-offset-1 col-lg-3 col-md-3 col-sm-5 last-type">
            <div class="type-incident inc-green">
                <div class="main-title-incident title-green">
                    Выполненные
                </div>
                <?php
                $d=date_create(date('Y-m-d', $_SERVER['REQUEST_TIME']));
                //echo date_format($d, 'Y-m-d');
                $d=$d->modify('+1 day');
                //echo date_format($d, 'Y-m-d');
                $current_date="".date_format($d, 'Y-m-d');
                //echo $current_date;

                $d=$d->modify('-8 day');
                //echo date_format($d, 'Y-m-d');
                $current_date_2="".date_format($d, 'Y-m-d');
                //echo $current_date_2;

                $incidient = Incidient::find(
                    [
                        'conditions' => 'status = 2 AND dateEnd between :date: AND :dats:',       //запрос
                        'bind' => [
                            'date' => $current_date_2,
                            'dats' => $current_date,
                        ],
                        'order' => 'dateEnd',    //сортировка
                        'offset'=> 0,       //смещение
                        //'limit' => 5,       //лимит записей
                    ]
                );
                echo "<div class=\"list-group\">";
                foreach ($incidient as $inc){
                //echo "<div>",$inc->id, "\n";
                //echo $inc->idInWiki,"</div><div>";
                $step=StepInIncidient::find(
                    [
                        'idIncidient = :ind:',       //запрос
                        'bind'=>[
                            'ind' => $inc->id,
                        ],
                        'order' => 'step',    //сортировка
                    ]
                );

                $summ=0;
                $int=0;
                foreach ($step as $s){
                    $summ++;
                    if($s->ending == NULL)
                        $int=$int+1;
                    //echo $s->id, "\n";
                    //echo $s->step, "\n", "</div>";
                }
                $percent=0.0;
                $percent=(($summ-$int)/$summ)*100.0;
                //$this->view->percent=$percent;

                //echo sprintf("%.24s...",$inc->title);//краткая форма
                //echo sprintf("%s",$inc->title);//
                //echo sprintf("%d",$inc->time);//
                //echo sprintf("%01.2f",$percent);//вывод числа в формате 2ух чисел после запятой
                $t=preg_split('/ /',$inc->dateStart);
                $date_i=$t[0]; //дата
                $time_i=$t[1]; //время

                $t_end=preg_split('/ /',$inc->dateEnd);
                $date_end_i=$t_end[0]; //дата
                $time_end_i=$t_end[1]; //время

                $end=preg_split('/-/',$date_end_i);
                $end_time=strval($end[2]).".".strval($end[1]).".".strval($end[0])."";

                echo "<a href=\"/incidient/",$inc->id,"\"","class=\"list-group-item list-group-desc\">";
                echo "<span class=\"percent\"><img src=\"/img/ok.svg\" width=\"18px\" alt=\"OK\">";

                echo $end_time;?><!--1.09.2018--></span><?php echo mb_substr($inc->title,0, 50).' ...';?>
                <div class="desc-incident">
                    <div class="row title-tooltip-inc">
                        <div class="col-lg-12">
                            <?php echo sprintf("%s",$inc->title);?>
                        </div>
                    </div>
                    <div class="row date-time-go">
                        <div class="col-lg-6 col-md-6 col-sm-6 text-left">Время начала</div>
                        <div class="col-lg-6 col-md-6 col-sm-6 text-left">Дата начала</div>
                    </div>
                    <div class="row date-time-go-bold">
                        <div class="col-lg-6 col-md-6 col-sm-6 text-left"><?php echo sprintf("%.5s",$time_i);//переделать формат для часов?></div>
                        <div class="col-lg-6 col-md-6 col-sm-6 text-left"><?php echo $t[0];//переделать формат для даты?></div>
                    </div>
                    <div class="row indication-block">
                        <div class="progress" style="height: 6px">
                            <div class="progress-bar progress-bar-green" role="progressbar" style="width: <?php echo $percent,"%"?>" aria-valuenow="<?php echo $percent,"%"?>" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <div class="indication text-center">Выполнено <?php echo sprintf("%01.2f",$percent),"%"?></div>
                    </div>
                </div>
                </a>
                <?php
                }
                ?>
            </div>
        </div>
<!--
</div>
        <div class="col-lg-offset-0 col-md-offset-0 col-sm-offset-1 col-lg-3 col-md-3 col-sm-5 last-type">
            <div class="type-incident inc-green">
                <div class="main-title-incident title-green">
                    Выполненные//двое суток
                </div>
                <div class="list-group">
                    <a href="implementation3.html" class="list-group-item list-group-desc">
                        <span class="percent"><img src="/img/ok.svg" width="18px" alt="OK"></span>1.09.2018 Действия при...
                        <div class="desc-incident">
                            <div class="row title-tooltip-inc">
                                <div class="col-lg-12">
                                    Действия при возникновении аварии с выбросом сильнодействующих ядовитых веществ
                                </div>
                            </div>
                            <div class="row date-time-go">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Время начала</div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Дата начала</div>
                            </div>
                            <div class="row date-time-go-bold">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">12 : 45</div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">30 Августа 2018</div>
                            </div>
                            <div class="row indication-block">
                                <div class="progress" style="height: 6px">
                                    <div class="progress-bar progress-bar-green" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="indication text-center">Выполнено 100%</div>
                            </div>
                        </div>
                    </a>
                    <a href="implementation3.html" class="list-group-item list-group-desc">
                        <span class="percent"><img src="/img/ok.svg" width="18px" alt="OK"></span>1.09.2018 Действия при...
                        <div class="desc-incident">
                            <div class="row title-tooltip-inc">
                                <div class="col-lg-12">
                                    Действия при возникновении аварии с выбросом сильнодействующих ядовитых веществ
                                </div>
                            </div>
                            <div class="row date-time-go">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Время начала</div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Дата начала</div>
                            </div>
                            <div class="row date-time-go-bold">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">12 : 45</div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">30 Августа 2018</div>
                            </div>
                            <div class="row indication-block">
                                <div class="progress" style="height: 6px">
                                    <div class="progress-bar progress-bar-green" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="indication text-center">Выполнено 100%</div>
                            </div>
                        </div>
                    </a>
                    <a href="implementation3.html" class="list-group-item list-group-desc">
                        <span class="percent"><img src="/img/ok.svg" width="18px" alt="OK"></span>1.09.2018 Действия при...
                        <div class="desc-incident">
                            <div class="row title-tooltip-inc">
                                <div class="col-lg-12">
                                    Действия при возникновении аварии с выбросом сильнодействующих ядовитых веществ
                                </div>
                            </div>
                            <div class="row date-time-go">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Время начала</div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Дата начала</div>
                            </div>
                            <div class="row date-time-go-bold">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">12 : 45</div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">30 Августа 2018</div>
                            </div>
                            <div class="row indication-block">
                                <div class="progress" style="height: 6px">
                                    <div class="progress-bar progress-bar-green" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="indication text-center">Выполнено 100%</div>
                            </div>
                        </div>
                    </a>
                    <a href="implementation3.html" class="list-group-item list-group-desc">
                        <span class="percent"><img src="/img/ok.svg" width="18px" alt="OK"></span>1.09.2018 Действия при...
                        <div class="desc-incident">
                            <div class="row title-tooltip-inc">
                                <div class="col-lg-12">
                                    Действия при возникновении аварии с выбросом сильнодействующих ядовитых веществ
                                </div>
                            </div>
                            <div class="row date-time-go">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Время начала</div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">Дата начала</div>
                            </div>
                            <div class="row date-time-go-bold">
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">12 : 45</div>
                                <div class="col-lg-6 col-md-6 col-sm-6 text-left">30 Августа 2018</div>
                            </div>
                            <div class="row indication-block">
                                <div class="progress" style="height: 6px">
                                    <div class="progress-bar progress-bar-green" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="indication text-center">Выполнено 100%</div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>-->
    </div>
</div>


<div class="container-fluid foot">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-3 col-md-3 col-sm-3">
            <img src="/img/logo.png" alt="Logo">
        </div>
        <div class="col-lg-7 col-md-7 col-sm-8 text-right foot-text">
            Программа для автоматизации действий оператора<br>
            по поиску и выполнению инструкций
        </div>
    </div>
</div>

<div class="modal-window text-center animated bounceInDown" id="modal-win">
    <form class="form-horizontal">
        <div class="form-group">
            <label for="inputLogin" class="control-label">Введите логин</label>
            <div class="col-lg-offset-2 col-lg-8" style="margin-top: 20px">
                <input type="text" class="form-control login-form" id="inputLogin" placeholder="Введите логин">
            </div>
        </div>
        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary smena-button">Смена</button>
                <button type="button" class="btn btn-primary smena-button smena-button-otmena" id="cancel">Отмена</button>
            </div>
        </div>
    </form>
</div>
<div class="overlay" id="overl"></div>

<script src="js/animate.js" type="text/javascript"></script>
<script src="/js/search.js" type="text/javascript"></script>
<script src="/js/modalWindow.js" type="text/javascript"></script>
</body>
</html>

<?php
/*
$result = Incidient::findFirst(63);
echo $result->idInWiki;

echo "<h1>Мчс Белгород</h1>";
echo $this->tag->linkTo("signup", "Зарегистрируйтесь здесь!");
echo $this->tag->linkTo("searchPage", "Поиск здесь!");
echo $this->tag->linkTo("loadPage", "Вывод здесь!");
echo "<div> <a> Блок </a> </div> <div> <a> Блок1 </a> </div>";



$incidient = Incidient::find(
    [
        'status = 0',       //запрос
        'order' => 'id',    //сортировка
        'offset'=> 2,       //смещение
        'limit' => 5,       //лимит записей
    ]
);

foreach ($incidient as $inc){
    echo "<div>",$inc->id, "\n";
    echo $inc->idInWiki,"</div><div>";
    $step=StepInIncidient::find(
            [
                'idIncidient = :ind:',       //запрос
                'bind'=>[
                       'ind' => $inc->id,
                ],
                'order' => 'step',    //сортировка
            ]
    );

    $summ=0;
    $int=0;
    foreach ($step as $s){
        $summ++;
        if($s->ending == NULL)
            $int=$int+1;
        echo $s->id, "\n";
        echo $s->step, "\n", "</div>";
    }
    $percent=0.0;
    $percent=(($summ-$int)/$summ)*100.0;
    //$this->view->percent=$percent;

    echo sprintf("%.24s...",$inc->title);//краткая форма
    echo sprintf("%s",$inc->title);//
    echo sprintf("%d",$inc->time);//
    echo sprintf("%01.2f",$percent);//вывод числа в формате 2ух чисел после запятой
}
*/
;